# Generated by Django 4.2.1 on 2023-05-18 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Nickname')),
                ('avatar', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')),
                ('timezone', models.CharField(choices=[('UTC', 'Universal Coordinated Time GMT'), ('ECT', 'European Central Time GMT+1:00'), ('EET', 'Eastern European Time GMT+2:00'), ('ART', '(Arabic) Egypt Standard Time GMT+2:00'), ('EAT', 'Eastern African Time GMT+3:00'), ('MET', 'Middle East Time GMT+3:30'), ('NET', 'Near East Time GMT+4:00'), ('PLT', 'Pakistan Lahore Time GMT+5:00'), ('IST', 'India Standard Time GMT+5:30'), ('BST', 'Bangladesh Standard Time GMT+6:00'), ('VST', 'Vietnam Standard Time GMT+7:00'), ('CTT', 'China Taiwan Time GMT+8:00'), ('JST', 'Japan Standard Time GMT+9:00'), ('ACT', 'Australia Central Time GMT+9:30'), ('AET', 'Australia Eastern Time GMT+10:00'), ('SST', 'Solomon Standard Time GMT+11:00'), ('NST', 'New Zealand Standard Time GMT+12:00'), ('MIT', 'Midway Islands Time GMT-11:00'), ('HST', 'Hawaii Standard Time GMT-10:00'), ('AST', 'Alaska Standard Time GMT-9:00'), ('PST', 'Pacific Standard Time GMT-8:00'), ('PNT', 'Phoenix Standard Time GMT-7:00'), ('MST', 'Mountain Standard Time GMT-7:00'), ('CST', 'Central Standard Time GMT-6:00'), ('EST', 'Eastern Standard Time GMT-5:00'), ('IET', 'Indiana Eastern Standard Time GMT-5:00'), ('PRT', 'Puerto Rico and US Virgin Islands Time GMT-4:00'), ('CNT', 'Canada Newfoundland Time GMT-3:30'), ('AGT', 'Argentina Standard Time GMT-3:00'), ('BET', 'Brazil Eastern Time GMT-3:00'), ('CAT', 'Central African Time GMT-1:00')], default='EET', max_length=3, verbose_name='timezone')),
                ('active_time_start', models.TimeField(default=datetime.time(9, 0))),
                ('active_time_end', models.TimeField(default=datetime.time(23, 0))),
                ('player_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
    ]
