# Generated by Django 4.2.1 on 2023-05-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amscrape.player')),
            ],
            options={
                'ordering': ['-expire_date'],
            },
        ),
    ]
