# Generated by Django 4.2.1 on 2023-05-19 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0002_playersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['nickname'], 'permissions': [('can_edit_gameserver', 'Can edit owned gameserver parameters')]},
        ),
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('arch', 'https://arch.the-reincarnation.com/cgi-bin/mainmenu.cgi'), ('guildwar', 'https://guildwar.the-reincarnation.com/cgi-bin/mainmenu.cgi'), ('blitz', 'https://blitz.the-reincarnation.com/cgi-bin/mainmenu.cgi'), ('solo', 'https://solo.the-reincarnation.com/cgi-bin/mainmenu.cgi'), ('lightning', 'https://lightning.the-reincarnation.com/cgi-bin/mainmenu.cgi'), ('beta', 'https://beta.the-reincarnation.com/cgi-bin/mainmenu.cgi')], default='beta', max_length=10, verbose_name='Server name')),
                ('oversummoning', models.BooleanField(default=True)),
                ('blackmarket', models.BooleanField(default=True)),
                ('bots', models.BooleanField(default=True)),
                ('ultimate', models.BooleanField(default=False)),
                ('permanentuniques', models.BooleanField(default=True)),
                ('period', models.DecimalField(decimal_places=0, help_text='Hours, usually like "Damage" status', max_digits=2)),
                ('maxturns', models.DecimalField(decimal_places=0, help_text='Max turns available to reach', max_digits=4)),
                ('playersession_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amscrape.playersession')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
