# Generated by Django 4.2.1 on 2023-05-22 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0002_gameserver_tracktarget_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameserver',
            name='period',
            field=models.PositiveIntegerField(default=1700, help_text='Average time to wait between tracking updates'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 0, 5, 22, 427432), null=True, verbose_name='Last visit'),
        ),
    ]
