# Generated by Django 4.2.1 on 2023-05-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0003_alter_player_options_gameserver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersession',
            old_name='player_id',
            new_name='player',
        ),
    ]
