# Generated by Django 4.2.1 on 2023-05-23 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0003_playergameserver_period_alter_player_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kingdomstat',
            name='game_server',
        ),
        migrations.RemoveField(
            model_name='kingdomstat',
            name='player',
        ),
        migrations.AddField(
            model_name='kingdomstat',
            name='player_game_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscrape.playergameserver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 11, 38, 14, 898187), null=True, verbose_name='Last visit'),
        ),
    ]
