# Generated by Django 4.2.1 on 2023-05-23 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0004_remove_kingdomstat_game_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktarget',
            name='player_game_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscrape.playergameserver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 14, 14, 32, 467460), null=True, verbose_name='Last visit'),
        ),
    ]
