# Generated by Django 4.2.1 on 2023-05-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0005_alter_playersession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_visits',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Visits'),
        ),
    ]
