# Generated by Django 4.2.1 on 2023-05-23 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0005_tracktarget_player_game_server_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kingdomstat',
            name='track_target',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 22, 34, 21, 265200), null=True, verbose_name='Last visit'),
        ),
    ]
