# Generated by Django 4.2.1 on 2023-05-23 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0006_remove_kingdomstat_track_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kingdomstat',
            name='value',
        ),
        migrations.AddField(
            model_name='kingdomstat',
            name='values',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 22, 42, 52, 834551), null=True, verbose_name='Last visit'),
        ),
    ]
