# Generated by Django 4.2.1 on 2023-05-23 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0007_remove_kingdomstat_value_kingdomstat_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 24, 2, 28, 36, 901239), null=True, verbose_name='Last visit'),
        ),
        migrations.AlterField(
            model_name='playersession',
            name='session_data',
            field=models.BinaryField(),
        ),
    ]
