# Generated by Django 4.2.1 on 2023-05-19 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0008_remove_player_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 20, 1, 18, 50, 942064), null=True, verbose_name='Last visit'),
        ),
    ]
