# Generated by Django 4.2.1 on 2023-05-24 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0008_alter_player_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 24, 12, 36, 11, 375351), null=True, verbose_name='Last visit'),
        ),
        migrations.AlterField(
            model_name='playersession',
            name='session_data',
            field=models.JSONField(),
        ),
    ]
