# Generated by Django 4.2.1 on 2023-05-25 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0009_alter_player_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 25, 13, 6, 24, 497244), null=True, verbose_name='Last visit'),
        ),
    ]
