# Generated by Django 4.2.1 on 2023-05-21 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0010_rename_playersession_id_gameserver_playersession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='playersession',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='player',
            field=models.ManyToManyField(to='amscrape.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 21, 18, 36, 13, 371163), null=True, verbose_name='Last visit'),
        ),
    ]
