# Generated by Django 4.2.1 on 2023-05-25 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0010_alter_player_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 25, 16, 43, 2, 387705), null=True, verbose_name='Last visit'),
        ),
    ]
