# Generated by Django 4.2.1 on 2023-05-21 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0011_remove_gameserver_playersession_gameserver_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='blackmarket',
            field=models.BooleanField(default=True, help_text='True if black market exists'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='bots',
            field=models.BooleanField(default=True, help_text='True if AI exists'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='oversummoning',
            field=models.BooleanField(default=True, help_text='True for oversummoning enviroment'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='period',
            field=models.DecimalField(decimal_places=0, help_text='Hours, usually "Damage" status last', max_digits=2),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='permanentuniques',
            field=models.BooleanField(default=True, help_text='True if uniques does not disappear'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='ultimate',
            field=models.BooleanField(default=True, help_text='True if ultimate spells, units exists'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 21, 21, 57, 48, 850846), null=True, verbose_name='Last visit'),
        ),
    ]
