# Generated by Django 4.2.1 on 2023-05-21 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0012_alter_gameserver_blackmarket_alter_gameserver_bots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='player',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 21, 21, 59, 44, 772611), null=True, verbose_name='Last visit'),
        ),
    ]
