# Generated by Django 4.2.1 on 2023-05-21 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0013_remove_gameserver_player_alter_player_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amscrape.gameserver'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 21, 22, 2, 1, 246060), null=True, verbose_name='Last visit'),
        ),
    ]
