# Generated by Django 4.2.1 on 2023-05-28 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0014_alter_player_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 28, 19, 17, 45, 951612), null=True, verbose_name='Last visit'),
        ),
    ]
