# Generated by Django 4.2.1 on 2023-05-21 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0014_player_game_server_alter_player_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 0, 19, 25, 687252), null=True, verbose_name='Last visit'),
        ),
    ]
