# Generated by Django 4.2.1 on 2023-05-28 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0015_alter_player_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingdomstat',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 28, 21, 33, 58, 689287), null=True, verbose_name='Last visit'),
        ),
    ]
