# Generated by Django 4.2.1 on 2023-05-21 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0015_alter_player_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_server',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 0, 23, 18, 158923), null=True, verbose_name='Last visit'),
        ),
        migrations.AddField(
            model_name='player',
            name='game_server',
            field=models.ManyToManyField(blank=True, null=True, to='amscrape.gameserver'),
        ),
    ]
