# Generated by Django 4.2.1 on 2023-05-22 00:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0016_remove_player_game_server_alter_player_last_visit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource, or anything to track', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='game_server',
            field=models.ManyToManyField(blank=True, to='amscrape.gameserver'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 3, 14, 25, 960525), null=True, verbose_name='Last visit'),
        ),
        migrations.CreateModel(
            name='KingdomStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amscrape.gameserver')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amscrape.player')),
                ('track_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amscrape.tracktarget')),
            ],
        ),
    ]
