# Generated by Django 4.2.1 on 2023-05-22 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0017_tracktarget_alter_player_game_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktarget',
            name='iterator_value',
            field=models.PositiveIntegerField(default=0, help_text='Position or index of the desired value'),
        ),
        migrations.AddField(
            model_name='tracktarget',
            name='keyword',
            field=models.CharField(default='', help_text='keyword of resource value', max_length=100),
        ),
        migrations.AddField(
            model_name='tracktarget',
            name='link',
            field=models.CharField(default='', help_text='url link to scrape resource', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 12, 16, 57, 100741), null=True, verbose_name='Last visit'),
        ),
        migrations.AlterField(
            model_name='tracktarget',
            name='name',
            field=models.CharField(default='', help_text='Name of the resource, or anything to track', max_length=100),
        ),
    ]
