# Generated by Django 4.2.1 on 2023-05-22 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0018_tracktarget_iterator_value_tracktarget_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='maxturns',
            field=models.PositiveIntegerField(default=0, help_text='Max turns available to reach'),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='period',
            field=models.PositiveIntegerField(default=0, help_text='Hours, usually "Damage" status last'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 12, 19, 12, 889226), null=True, verbose_name='Last visit'),
        ),
    ]
