# Generated by Django 4.2.1 on 2023-05-22 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0019_alter_gameserver_maxturns_alter_gameserver_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracktarget',
            name='name',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 20, 11, 40, 567874), null=True, verbose_name='Last visit'),
        ),
        migrations.AlterField(
            model_name='tracktarget',
            name='iterator_value',
            field=models.PositiveIntegerField(default=0, help_text='Index of value, if it is a table, first=0'),
        ),
        migrations.AlterField(
            model_name='tracktarget',
            name='keyword',
            field=models.CharField(default='', help_text='keyword of scraped object', max_length=100),
        ),
        migrations.AlterField(
            model_name='tracktarget',
            name='link',
            field=models.CharField(default='', help_text='url - link where to search for object', max_length=200),
        ),
    ]
