# Generated by Django 4.2.1 on 2023-05-28 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0019_alter_player_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingdomstat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 28, 22, 53, 4, 164870), null=True, verbose_name='Last visit'),
        ),
        migrations.AlterField(
            model_name='playergameserver',
            name='period',
            field=models.PositiveIntegerField(default=15, help_text='Average time to wait between tracking updates'),
        ),
    ]
