# Generated by Django 4.2.1 on 2023-05-28 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0020_alter_kingdomstat_timestamp_alter_player_last_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameserver',
            name='only_night_tracker',
            field=models.BooleanField(default=True, help_text='Track only at nights'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 28, 23, 30, 32, 476742), null=True, verbose_name='Last visit'),
        ),
        migrations.AlterField(
            model_name='playergameserver',
            name='period',
            field=models.PositiveIntegerField(default=15, help_text='Minutes between tracking updates'),
        ),
    ]
