# Generated by Django 4.2.1 on 2023-05-22 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscrape', '0020_remove_tracktarget_name_alter_player_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 20, 40, 0, 337867), null=True, verbose_name='Last visit'),
        ),
        migrations.AlterField(
            model_name='tracktarget',
            name='keyword',
            field=models.CharField(default='', help_text='Keyword of tracking object, case sensitive', max_length=100),
        ),
    ]
